# Docker Compose for local development
version: '3.8'

services:
  renewable-energy-app-dev:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - AZURE_SQL_SERVER=${AZURE_SQL_SERVER}
      - AZURE_SQL_USERNAME=${AZURE_SQL_USERNAME}
      - AZURE_SQL_PASSWORD=${AZURE_SQL_PASSWORD}
      - AZURE_SQL_DATABASE=${AZURE_SQL_DATABASE}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - .:/app
      - ./logs:/app/logs
    networks:
      - app-network
    command: python app.py

networks:
  app-network:
    driver: bridge
